### ISSUE TITLE
Someone is interested

### ISSUE THREAD

**Issue by pmodin** [zsugabubus/dotfiles#1]
Hey,

just wanted you to know that after 3f59830b22bb1803d9ded0e71e52b6f8b49534ed, and reading the commit message, that someone did find value in what you did :smile:

I *think* that I was using the mbsyncrc parts, but opening this issue has been on my todo list for too long, so I don't recall any more.

I solved it for my setup, so feel free to close this at will, no action required, but, thank you!

**Comment by zsugabubus** [comment]
Hi there!

Glad to hear that!
